### ISSUE TITLE
Calendario de consultas médico

### ISSUE THREAD

**Issue by vale9003** [leokraken/project.core#26]
Entro al calendario como medico/medico, veo que esta coloreada el día de la consulta que tengo asignada pero después no puedo hacer nada. Si hago click en el día no me muestra nada.

**Comment by leokraken** [comment]
Aparentemente lo veo bien.
![screenshot from 2016-04-10 22 16 11](https://cloud.githubusercontent.com/assets/8573259/14414486/0dd25416-ff6a-11e5-8a80-e981dcd5ac88.png)
