### ISSUE TITLE
Ver Especialidad, no se estan cargando bien los valores en el modal

### ISSUE THREAD

**Issue by vale9003** [leokraken/project.core#29]
Al dirigirse a la opcion Especialidades >Listar, y seleccionar el botón azul de las grillas no se están cargando bien los datos de la especialidad en el modal, todos los campos aparecen vacíos.

**Comment by leokraken** [comment]
Traducciones en especialidad, al seleccionar idioma, se presenta el nombre y la descripción, no es bug.
