### ISSUE TITLE
Aplicacion IONIC - Error al loguearse nombre de usuario erroneo

### ISSUE THREAD

**Issue by vale9003** [leokraken/project.core#39]
Inicio sesión con usuario paciente/paciente luego cierro sesión. Inicio sesión con medico/medico. Me aparece en el inicio el nombre de usuario paciente paciente. Vuelvo a cerrar sesión e inicio sesión nuevamente con medico/medico y ahi si me aparece Medico Mágico como nombre de usuario.

**Comment by leokraken** [comment]
This issue is fixed on latest release , you can download here the apk.
[android-debug.apk.zip](https://github.com/leokraken/project.core/files/218467/android-debug.apk.zip)
